### ISSUE TITLE
libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rsignell-usgs** [conda-forge/gmt-feedstock#2]
I just did `conda install gmt` into a Python 3 environment on an `openSUSE Leap 42.1 (x86_64)` system:
```
(IOOS3) rsignell@gamone:~> conda list gmt
# packages in environment at /home/rsignell/miniconda3/envs/IOOS3:
#
gmt                       5.3.3                         0    conda-forge
```

When when I try to run a GMT command, I get: 
```
(IOOS3) rsignell@gamone:~> xyz2grd --help
xyz2grd: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
```

**Comment by ocefpaf** [comment]
`gmt` is linking to `mkl` because `defatuls` numpy was pulled during the build. The workaround for now is to force install `mkl` (and it should also change your `numpy` but it did not in my case resulting in a broken `numpy` :weary:).

The real solution is to avoid the linkage on the build so `gmt` can work with both versions of `numpy` installed. My next PR should do that.
